FROM python:3.10-slim

WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy project metadata
COPY ../pyproject.toml ../poetry.lock ./

# Install dependencies (no venv)
RUN poetry config virtualenvs.create false && \
    poetry install --no-root --no-interaction --no-ansi

# Copy API and source code
COPY . .
COPY ../src ./src

EXPOSE 8000

CMD ["uvicorn", "qpp:app", "--host", "0.0.0.0", "--port", "8000"]
